### PR TITLE
action for verifying author of vendor.schema.json

### PR DESCRIPTION
**Pull request by chirag-jn**
add action for verifying author of changes in vendor.schema.json

### CODE REVIEW

**Comment by chirag-jn** [comment]
To use this action, please set a new environment variable `TOKEN` which will be a [classic](https://github.com/settings/tokens) GitHub token.
For specifying the scope, please give the scope as `repo:status`, `repo:public_repo` and `read:org`

**Comment by svonava** [comment]
@chirag-jn are you still trying to merge this in? anything I can do to help?

**Comment by prrao87** [comment]
Just checking in on the intent for this going forward @svonava-superlinked & @AruneshSingh.

**Comment by chirag-jn** [comment]
> Just checking in on the intent for this going forward @svonava-superlinked & @AruneshSingh.

Yep we need this. The PR missed my backlog tracker. I’ll rebase the change and make updates today.

**Comment by svonava** [comment]
> > Just checking in on the intent for this going forward @svonava-superlinked & @AruneshSingh.
> 
> Yep we need this. The PR missed my backlog tracker. I’ll rebase the change and make updates today.

@chirag-jn how are we doing here?

**Comment by chirag-jn** [comment]
Apologies for the delay.
@AruneshSingh can you please create a repo secret with the key `SUPERLINKED_PAT_TOKEN` which would have its value as a PAT token with `read:org` and `repo` scope at least.

**Comment by AruneshSingh** [comment]
> Apologies for the delay. @AruneshSingh can you please create a repo secret with the key `SUPERLINKED_PAT_TOKEN` which would have its value as a PAT token with `read:org` and `repo` scope at least.

Done, created with name `VDB_CONTRIBUTION_CHECK_TOKEN`

**Pull request closed without merging**
